plugins:
  - react
extends:
  - eslint:recommended
  - airbnb
  - plugin:react/recommended
env:
  browser: true
  node: true
rules:
  indent:
    - error
    - 4
  react/jsx-indent:
    - 1
    - 4
  react/jsx-filename-extension:
    - 1
    - extensions:
      - .js
      - .jsx
