version: '3'
 
services:
    db:
      image: mysql:5.7
      environment:
        - MYSQL_DATABASE=pottpokal
        - MYSQL_USER=pottpokal
        - MYSQL_PASSWORD=secret
        - MYSQL_ROOT_PASSWORD=root
      ports:
            - "3306:3306"
      networks:
        pottpokal:
          aliases:
            - database
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        PMA_ARBITRARY: 1
        PMA_HOST: database
        PMA_PORT: 3306
        PMA_USER: root
        PMA_PASSWORD: root
      ports:
        - "80:80"
      networks:
        pottpokal:
networks:
  pottpokal:
